version: "3.7"

services:
  plugin:
    command: "bash"
    tty: true
    stdin_open: true
    container_name: "ensl_plugin"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
     - "./build:/var/build"